### ISSUE TITLE
Bug and Suggestion

### ISSUE THREAD

**Issue by aspectdev-ph** [mashwishi/Kohee#4]
Reset data when closed:
Also First letter is stuck for some reason:
![image](https://user-images.githubusercontent.com/32452006/209935785-8022b903-6e6a-41ae-95c3-b2853df496dc.png)

**Comment by aspectdev-ph** [comment]
When ever trying to edit it reset the button name :
![image](https://user-images.githubusercontent.com/32452006/209936432-54ae34be-420c-46d5-abbe-efd1f9e9ffbc.png)

**Comment by mashwishi** [comment]
issue solve, kindly reopen if still occurs.

**Comment by aspectdev-ph** [comment]
will retest things later

**Comment by aspectdev-ph** [comment]
### Reset input field when ever pressed close button :
![image](https://user-images.githubusercontent.com/32452006/210167409-d8f85293-419f-4b3e-ad7e-b52272ab074c.png)


> When ever you close the model it would reset the form . It feels weird that the previous input is still in the text box after cloed

**Comment by mashwishi** [comment]
The field will now reset when pressing cancel button to add and edit at version 1.6.3
