### ISSUE TITLE
Add Meta Data information on user profile page 

### ISSUE THREAD

**Issue by aspectdev-ph** [mashwishi/Kohee#5]
https://kohee.app/ejayztv

Add meta data on this page .so when shared in social media like messenger /facebook/ site it can have preview or info:
![image](https://user-images.githubusercontent.com/32452006/209936830-3da4dc21-ced6-40e4-8e18-ceea6ddc6d6b.png)
Something like this :
![image](https://user-images.githubusercontent.com/32452006/209936970-41996eb7-c599-4939-a59f-a2773ab2f7a9.png)

**Comment by mashwishi** [comment]
issue solved version 1.4.9
