### ISSUE TITLE
Link type not changing when selecting link types (ex:snapchat/messenger)

### ISSUE THREAD

**Issue by aspectdev-ph** [mashwishi/Kohee#9]
Link is not updating in dropdown menu . Also i think it would be proper to automatically add the link sample in button link input field and button text (eg: when user select youtube it would automatically add Youtube in button text and https://youtube.com/@Handle)
https://user-images.githubusercontent.com/32452006/210167654-8d2eba31-3968-4f73-8f64-3fc161c007f8.mp4

**Comment by mashwishi** [comment]
Feature for URL has been approved and issue has been fixed at version 1.6.3
